---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipit
  namespace: shipit
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - shipit.unboundsec.dev
    secretName: shipit-tls
  rules:
  - host: shipit.unboundsec.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shipit
            port:
              number: 80
